Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 6
   using_raw_point: 1
   point_step: 1
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 0        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]



r3live_vio:
   image_width: 960
   image_height: 600
   camera_intrinsic:
      [643.5951111267952, 0.0, 475.2215406900663,
      0.0,  642.6656126857330, 307.4120184196884,
      0.0, 0.0, 1.0 ] 
   camera_dist_coeffs: [-0.061606731291039, 0.100129900708930, 0.0, 0.0, 0.0]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. form camera-LiDAR calibration.
   # T_livox_gray0
   camera_ext_R:  
        [ 3.50926032e-04,  3.99988891e-03,  9.99991676e-01,
          -9.99992741e-01,  3.92046335e-03,  3.33853944e-04,
          -3.91827113e-03, -9.99984478e-01,  4.00126248e-03 ]
   # camera_ext_t: [0.050166, 0.0474116, -0.0312415] 
   camera_ext_t: [ 4.76032408e-02,1.46686091e-01,6.70716531e-02] 
   # Rough extrinsic value, form CAD model, is not correct enough, but can be online calibrated in our datasets.
   # camera_ext_R:
   #    [0, 0, 1,
   #     -1, 0, 0,
   #     0, -1, 0]
   # camera_ext_t: [0,0,0] 
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30